name: FastAPI Deploy

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.Suraj@?123 }}" | docker login -u "${{ secrets.surajkakade }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.surajkakade }}/fastapi-app:latest .
          docker push ${{ secrets.surajkakade }}/fastapi-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.192.168.43.62 }} << 'EOF'
            docker pull ${{ secrets.surajkakade }}/fastapi-app:latest
            docker-compose down && docker-compose up -d
EOF
